# Generated by Django 3.1.2 on 2020-10-22 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nid',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator('^(\\d{10}|\\d{13}|\\d{17})$', message='Numeric 10/13/17 digits (ex: 1234567890)')], verbose_name='National ID'),
        ),
    ]
