# Generated by Django 3.1.4 on 2020-12-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_auto_20201022_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='profile',
            name='division',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Division'),
        ),
        migrations.AddField(
            model_name='profile',
            name='postal',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='profile',
            name='thana',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Thana'),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
